### ISSUE TITLE
Problem to install 

### ISSUE THREAD

**Issue by bandicoot32** [Bunkerbewohner/tidal-music-linux#18]
After runing command  npm start
I get this error 
npm ERR! missing script: start

**Comment by deme3** [comment]
Sorry! My bad, I'll file another PR asap

**Comment by RW0PG** [comment]
Have you already fixed this issue? Because I have got exactly the same problem - after the installation there's an error:
missing script: start.
I have been trying somehow to fix it by myself but I think that I can't.  

edit;
sh: 1: electron: not found
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! tidal-music-linux@1.0.0 start: `electron main.js`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the tidal-music-linux@1.0.0 start script.

Now after adding the script with the start I have the error like ^
