### ISSUE TITLE
Couldn't grab media keys, this system may be not running GNOME

### ISSUE THREAD

**Issue by ImSugarFree** [Bunkerbewohner/tidal-music-linux#25]
```
# electron main.js
Couldn't grab media keys, this system may be not running GNOME

# uname -a
Linux 4.9.0-8-amd64 #1 SMP Debian 4.9.130-2 (2018-10-27) x86_64 GNU/Linux

# plasmashell --version
plasmashell 5.8.6
```
I know I'm not running GNOME, but shouldn't it run independently?

**Comment by Mastermindzh** [comment]
I submitted a PR which fixes this, you can look at it and apply the fix yourself as well.

**Comment by ndrewtl** [comment]
I actually wrote a more general solution to this problem that should work-- with all window managers / desktop environments. I've been unofficially maintaining this project and I'm not running GNOME. My patch is on the `develop` branch-- maybe try it out?

**Comment by Mastermindzh** [comment]
As I had no interest in using media keys but rather other key combos (I'm on i3...).
I've actually implemented an API which controls the app on my own version.

Excuse the comment spam, I just cleaned my system and uninstalled this tidal version because I've been using my own for a while now and was reminded of my open issue here.

**Comment by ImSugarFree** [comment]
Can't test it... I don't use Tidal any more.
