### ISSUE TITLE
Impossible to connect with Facebook account

### ISSUE THREAD

**Issue by bastyen** [Bunkerbewohner/tidal-music-linux#5]
Cookies are disable in electron app. Need to enable to use facebook account (and twitter too maybe).

**Comment by bastyen** [comment]
I think we can do nothing. Because web security and iFrame

**Comment by dmitry-saritasa** [comment]
+1 can't use it due to social auth / cookie failure

**Comment by alexemilberg** [comment]
Same thing with twitter, cannot login with it.

**Comment by Bunkerbewohner** [comment]
@BastienAlvez is right, the problem is the lack of cookies. There is a [cookies plugin](https://www.npmjs.com/package/electron-cookies) for electron which could help and seems to be easily integrated. Though since I don't have an active Tidal subscription right now I couldn't test it. 
So if anyone wants to have a go at it, feel free to create a PR. :-)
